// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

/// Bindings for `src/bridge/c_api.h`.
///
/// Regenerate bindings with `dart run ffigen --config ffigen.yaml`.
///
class SelectionHookFlutterBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  SelectionHookFlutterBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  SelectionHookFlutterBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  /// Create a new SelectionHook instance.
  ///
  /// Allocates and initializes platform-specific resources.
  /// Call sh_set_selection_callback BEFORE sh_start.
  ///
  /// @return Opaque handle, or NULL on failure. On failure, call
  /// sh_last_global_error() for details.
  /// @thread_safety Safe from any thread.
  ffi.Pointer<SelectionHook> sh_create() {
    return _sh_create();
  }

  late final _sh_createPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<SelectionHook> Function()>>(
        'sh_create',
      );
  late final _sh_create = _sh_createPtr
      .asFunction<ffi.Pointer<SelectionHook> Function()>();

  /// Destroy a SelectionHook instance.
  ///
  /// Caller MUST ensure sh_stop has returned before calling sh_destroy.
  /// Releases all native resources.
  ///
  /// @param hook Instance to destroy. May be NULL (no-op).
  /// @thread_safety Safe from any thread. Not safe if callback is in-flight
  /// (caller responsibility to serialize with sh_stop).
  void sh_destroy(ffi.Pointer<SelectionHook> hook) {
    return _sh_destroy(hook);
  }

  late final _sh_destroyPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<SelectionHook>)>
      >('sh_destroy');
  late final _sh_destroy = _sh_destroyPtr
      .asFunction<void Function(ffi.Pointer<SelectionHook>)>();

  /// Start monitoring text selections.
  ///
  /// Initializes platform-specific hooks and begins monitoring. A callback
  /// must have been registered via sh_set_selection_callback before calling
  /// this function.
  ///
  /// On macOS, this will call AXIsProcessTrustedWithOptions with prompt
  /// before any AXAPI calls. The user must grant accessibility permissions.
  ///
  /// @param hook Valid SelectionHook instance.
  /// @return SH_OK (0) on success, negative error code on failure.
  /// @thread_safety Safe from any thread. The callback will be invoked from
  /// native threads.
  int sh_start(ffi.Pointer<SelectionHook> hook) {
    return _sh_start(hook);
  }

  late final _sh_startPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<SelectionHook>)>>(
        'sh_start',
      );
  late final _sh_start = _sh_startPtr
      .asFunction<int Function(ffi.Pointer<SelectionHook>)>();

  /// Stop monitoring text selections.
  ///
  /// Unregisters platform hooks and blocks until no callback is in-flight.
  /// After sh_stop returns, it is safe to sh_destroy and/or close the
  /// NativeCallable.
  ///
  /// @param hook Valid SelectionHook instance.
  /// @return SH_OK (0) on success, SH_ERR_NOT_RUNNING if not started.
  /// @thread_safety Safe from any thread. Blocks until in-flight callbacks
  /// complete.
  int sh_stop(ffi.Pointer<SelectionHook> hook) {
    return _sh_stop(hook);
  }

  late final _sh_stopPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<SelectionHook>)>>(
        'sh_stop',
      );
  late final _sh_stop = _sh_stopPtr
      .asFunction<int Function(ffi.Pointer<SelectionHook>)>();

  /// Check if the hook is currently running.
  ///
  /// @param hook Valid SelectionHook instance.
  /// @return 1 if running, 0 if not running.
  /// @thread_safety Safe from any thread.
  int sh_is_running(ffi.Pointer<SelectionHook> hook) {
    return _sh_is_running(hook);
  }

  late final _sh_is_runningPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<SelectionHook>)>>(
        'sh_is_running',
      );
  late final _sh_is_running = _sh_is_runningPtr
      .asFunction<int Function(ffi.Pointer<SelectionHook>)>();

  /// Get the current text selection synchronously.
  ///
  /// Returns a snapshot of the current selection, or NULL if no text is
  /// selected or the hook is not running.
  ///
  /// The returned SHSelectionData* is owned by the library. It is valid until
  /// the pointer returned by sh_get_current_selection.
  /// Caller owns the returned data — MUST call sh_free_selection_data.
  ///
  /// @param hook Valid SelectionHook instance.
  /// @return Current selection data (caller-owned), or NULL.
  /// @thread_safety Safe from any thread.
  ffi.Pointer<SHSelectionData> sh_get_current_selection(
    ffi.Pointer<SelectionHook> hook,
  ) {
    return _sh_get_current_selection(hook);
  }

  late final _sh_get_current_selectionPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<SHSelectionData> Function(ffi.Pointer<SelectionHook>)
        >
      >('sh_get_current_selection');
  late final _sh_get_current_selection = _sh_get_current_selectionPtr
      .asFunction<
        ffi.Pointer<SHSelectionData> Function(ffi.Pointer<SelectionHook>)
      >();

  /// Free a SHSelectionData previously returned by sh_get_current_selection.
  ///
  /// Frees the heap-allocated copy including its string fields.
  /// Safe to call with NULL.
  ///
  /// @param hook Valid SelectionHook instance (unused, kept for API consistency).
  /// @param data Pointer returned by sh_get_current_selection, or NULL (no-op).
  /// @thread_safety Safe from any thread.
  void sh_free_selection_data(
    ffi.Pointer<SelectionHook> hook,
    ffi.Pointer<SHSelectionData> data,
  ) {
    return _sh_free_selection_data(hook, data);
  }

  late final _sh_free_selection_dataPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<SelectionHook>,
            ffi.Pointer<SHSelectionData>,
          )
        >
      >('sh_free_selection_data');
  late final _sh_free_selection_data = _sh_free_selection_dataPtr
      .asFunction<
        void Function(ffi.Pointer<SelectionHook>, ffi.Pointer<SHSelectionData>)
      >();

  /// Register the text selection callback.
  ///
  /// Stores a function pointer that will be called from native threads when
  /// a text selection is detected. Must be called before sh_start.
  ///
  /// The callback will be invoked from native system threads. Use
  /// `NativeCallable<Void Function(Pointer<SHSelectionData>)>.listener(...)`
  /// on the Dart side to receive these callbacks.
  ///
  /// Calling this after sh_start has undefined behavior — stop first.
  ///
  /// @param hook Valid SelectionHook instance.
  /// @param callback Function pointer, or NULL to unregister.
  /// @return SH_OK (0) on success.
  /// @thread_safety May be called from any thread before sh_start.
  int sh_set_selection_callback(
    ffi.Pointer<SelectionHook> hook,
    SHSelectionCallback callback,
  ) {
    return _sh_set_selection_callback(hook, callback);
  }

  late final _sh_set_selection_callbackPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<SelectionHook>, SHSelectionCallback)
        >
      >('sh_set_selection_callback');
  late final _sh_set_selection_callback = _sh_set_selection_callbackPtr
      .asFunction<
        int Function(ffi.Pointer<SelectionHook>, SHSelectionCallback)
      >();

  /// Get the last error description for this hook instance.
  ///
  /// Returns a human-readable description of the last error that occurred on
  /// the calling thread. The returned string is owned by the library and is
  /// valid until the next call to sh_last_error from the same thread.
  ///
  /// @param hook Valid SelectionHook instance.
  /// @return Error description (UTF-8, NUL-terminated), or NULL if no error.
  /// @thread_safety Thread-local — each thread gets its own error state.
  ffi.Pointer<ffi.Char> sh_last_error(ffi.Pointer<SelectionHook> hook) {
    return _sh_last_error(hook);
  }

  late final _sh_last_errorPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<SelectionHook>)
        >
      >('sh_last_error');
  late final _sh_last_error = _sh_last_errorPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<SelectionHook>)>();

  /// Get the last global error description (for constructor failures).
  ///
  /// Used when sh_create returns NULL. Returns a description of why creation
  /// failed. The returned string is owned by the library and is valid until
  /// the next call to sh_last_global_error.
  ///
  /// @return Error description (UTF-8, NUL-terminated), or NULL if no error.
  /// @thread_safety Thread-safe. Returns the most recent global error.
  ffi.Pointer<ffi.Char> sh_last_global_error() {
    return _sh_last_global_error();
  }

  late final _sh_last_global_errorPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
        'sh_last_global_error',
      );
  late final _sh_last_global_error = _sh_last_global_errorPtr
      .asFunction<ffi.Pointer<ffi.Char> Function()>();

  /// Register a callback for mouse/wheel events.
  ///
  /// The callback is invoked from native system threads. Data pointers are
  /// valid only for the duration of the callback — Dart MUST copy immediately.
  ///
  /// Must be called before sh_start. Calling after sh_start has undefined
  /// behavior — stop first.
  ///
  /// @param hook Valid SelectionHook instance.
  /// @param callback Function pointer, or NULL to unregister.
  /// @return SH_OK (0) on success.
  /// @thread_safety May be called from any thread before sh_start.
  int sh_set_mouse_callback(
    ffi.Pointer<SelectionHook> hook,
    SHMouseCallback callback,
  ) {
    return _sh_set_mouse_callback(hook, callback);
  }

  late final _sh_set_mouse_callbackPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<SelectionHook>, SHMouseCallback)
        >
      >('sh_set_mouse_callback');
  late final _sh_set_mouse_callback = _sh_set_mouse_callbackPtr
      .asFunction<int Function(ffi.Pointer<SelectionHook>, SHMouseCallback)>();

  /// Enable mouse-move events.
  ///
  /// Mouse-move events are high-CPU on some platforms. Only enable if your
  /// application needs per-pixel mouse tracking.
  ///
  /// @param hook Valid SelectionHook instance (must be started).
  /// @return SH_OK (0) on success, negative error code on failure.
  /// @thread_safety Safe from any thread.
  int sh_enable_mouse_move(ffi.Pointer<SelectionHook> hook) {
    return _sh_enable_mouse_move(hook);
  }

  late final _sh_enable_mouse_movePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<SelectionHook>)>>(
        'sh_enable_mouse_move',
      );
  late final _sh_enable_mouse_move = _sh_enable_mouse_movePtr
      .asFunction<int Function(ffi.Pointer<SelectionHook>)>();

  /// Disable mouse-move events.
  ///
  /// Stops receiving mouse-move callbacks. Mouse-down, mouse-up, and
  /// mouse-wheel events are unaffected.
  ///
  /// @param hook Valid SelectionHook instance (must be started).
  /// @return SH_OK (0) on success, negative error code on failure.
  /// @thread_safety Safe from any thread.
  int sh_disable_mouse_move(ffi.Pointer<SelectionHook> hook) {
    return _sh_disable_mouse_move(hook);
  }

  late final _sh_disable_mouse_movePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<SelectionHook>)>>(
        'sh_disable_mouse_move',
      );
  late final _sh_disable_mouse_move = _sh_disable_mouse_movePtr
      .asFunction<int Function(ffi.Pointer<SelectionHook>)>();

  /// Register a callback for keyboard events.
  ///
  /// The callback is invoked from native system threads. Data pointers are
  /// valid only for the duration of the callback — Dart MUST copy immediately.
  ///
  /// Must be called before sh_start. Calling after sh_start has undefined
  /// behavior — stop first.
  ///
  /// @param hook Valid SelectionHook instance.
  /// @param callback Function pointer, or NULL to unregister.
  /// @return SH_OK (0) on success.
  /// @thread_safety May be called from any thread before sh_start.
  int sh_set_keyboard_callback(
    ffi.Pointer<SelectionHook> hook,
    SHKeyboardCallback callback,
  ) {
    return _sh_set_keyboard_callback(hook, callback);
  }

  late final _sh_set_keyboard_callbackPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<SelectionHook>, SHKeyboardCallback)
        >
      >('sh_set_keyboard_callback');
  late final _sh_set_keyboard_callback = _sh_set_keyboard_callbackPtr
      .asFunction<
        int Function(ffi.Pointer<SelectionHook>, SHKeyboardCallback)
      >();

  /// Apply a full configuration to the hook.
  ///
  /// All fields in SHSelectionConfig are optional — pass 0/0.0 for defaults.
  /// Overwrites any previously set configuration. Must be called before sh_start.
  ///
  /// @param hook Valid SelectionHook instance.
  /// @param config Pointer to configuration struct.
  /// @return SH_OK (0) on success, negative error code on failure.
  /// @thread_safety May be called from any thread before sh_start.
  int sh_set_config(
    ffi.Pointer<SelectionHook> hook,
    ffi.Pointer<SHSelectionConfig> config,
  ) {
    return _sh_set_config(hook, config);
  }

  late final _sh_set_configPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<SelectionHook>,
            ffi.Pointer<SHSelectionConfig>,
          )
        >
      >('sh_set_config');
  late final _sh_set_config = _sh_set_configPtr
      .asFunction<
        int Function(ffi.Pointer<SelectionHook>, ffi.Pointer<SHSelectionConfig>)
      >();

  /// Enable or disable passive mode.
  ///
  /// In passive mode, text selection is only detected when the user explicitly
  /// triggers it (e.g., via a system shortcut), rather than automatically on
  /// every mouse-release.
  ///
  /// @param hook Valid SelectionHook instance (must be started).
  /// @param passive 1=enable passive mode, 0=disable.
  /// @return SH_OK (0) on success, negative error code on failure.
  /// @thread_safety Safe from any thread.
  int sh_set_passive_mode(ffi.Pointer<SelectionHook> hook, int passive) {
    return _sh_set_passive_mode(hook, passive);
  }

  late final _sh_set_passive_modePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<SelectionHook>, ffi.Int)
        >
      >('sh_set_passive_mode');
  late final _sh_set_passive_mode = _sh_set_passive_modePtr
      .asFunction<int Function(ffi.Pointer<SelectionHook>, int)>();

  /// Write text to the system clipboard.
  ///
  /// On Linux, this function returns SH_ERR_GENERIC — clipboard write-back
  /// is not supported on Linux via this API.
  ///
  /// @param hook Valid SelectionHook instance.
  /// @param text UTF-8 NUL-terminated string to place on the clipboard.
  /// @return SH_OK (0) on success, negative error code on failure.
  /// @thread_safety Safe from any thread.
  int sh_write_clipboard(
    ffi.Pointer<SelectionHook> hook,
    ffi.Pointer<ffi.Char> text,
  ) {
    return _sh_write_clipboard(hook, text);
  }

  late final _sh_write_clipboardPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<SelectionHook>, ffi.Pointer<ffi.Char>)
        >
      >('sh_write_clipboard');
  late final _sh_write_clipboard = _sh_write_clipboardPtr
      .asFunction<
        int Function(ffi.Pointer<SelectionHook>, ffi.Pointer<ffi.Char>)
      >();

  /// Read text from the system clipboard.
  ///
  /// Returns the current clipboard contents as UTF-8, or NULL if the
  /// clipboard is empty or contains non-text data.
  ///
  /// On Linux, this function returns NULL — clipboard read-back is not
  /// supported on Linux via this API.
  ///
  /// The returned string is owned by the library and is valid until the
  /// next call to sh_read_clipboard from the same thread.
  ///
  /// @param hook Valid SelectionHook instance.
  /// @return Clipboard text (library-owned), or NULL.
  /// @thread_safety Safe from any thread.
  ffi.Pointer<ffi.Char> sh_read_clipboard(ffi.Pointer<SelectionHook> hook) {
    return _sh_read_clipboard(hook);
  }

  late final _sh_read_clipboardPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<SelectionHook>)
        >
      >('sh_read_clipboard');
  late final _sh_read_clipboard = _sh_read_clipboardPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<SelectionHook>)>();

  /// Check if process is trusted for accessibility (macOS only).
  ///
  /// On non-macOS platforms, always returns 1 (trusted).
  ///
  /// @param hook Valid SelectionHook instance.
  /// @return 1 if trusted or non-macOS platform, 0 if not trusted.
  /// @thread_safety Safe from any thread.
  int sh_mac_is_process_trusted(ffi.Pointer<SelectionHook> hook) {
    return _sh_mac_is_process_trusted(hook);
  }

  late final _sh_mac_is_process_trustedPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<SelectionHook>)>>(
        'sh_mac_is_process_trusted',
      );
  late final _sh_mac_is_process_trusted = _sh_mac_is_process_trustedPtr
      .asFunction<int Function(ffi.Pointer<SelectionHook>)>();

  /// Try to request accessibility permissions (macOS only, may show dialog).
  ///
  /// On non-macOS platforms, always returns SH_OK.
  ///
  /// @param hook Valid SelectionHook instance.
  /// @return SH_OK (0) on success, negative error code on failure.
  /// @thread_safety Safe from any thread. May present a system dialog — be
  /// mindful of UI context when calling.
  int sh_mac_request_process_trust(ffi.Pointer<SelectionHook> hook) {
    return _sh_mac_request_process_trust(hook);
  }

  late final _sh_mac_request_process_trustPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<SelectionHook>)>>(
        'sh_mac_request_process_trust',
      );
  late final _sh_mac_request_process_trust = _sh_mac_request_process_trustPtr
      .asFunction<int Function(ffi.Pointer<SelectionHook>)>();
}

final class SelectionHook extends ffi.Opaque {}

/// 2D coordinate in screen pixels.
final class SHPoint extends ffi.Struct {
  @ffi.Int32()
  external int x;

  @ffi.Int32()
  external int y;
}

/// Text selection data returned via callback or sh_get_current_selection.
///
/// All `const char*` fields are owned by the library. In callbacks, they are
/// valid only for the duration of the callback. In sh_get_current_selection, they
/// are valid until the next call or until sh_free_selection_data.
///
/// Sentinel value for unavailable coordinates: -99999 (INVALID_COORDINATE).
/// On Linux, startTop/startBottom/endTop/endBottom are always INVALID_COORDINATE.
/// On Linux Wayland, mouseStart/mouseEnd may also be INVALID_COORDINATE.
final class SHSelectionData extends ffi.Struct {
  /// Selected text content (UTF-8, NUL-terminated).
  external ffi.Pointer<ffi.Char> text;

  /// Program name that triggered the selection (UTF-8, NUL-terminated).
  external ffi.Pointer<ffi.Char> program_name;

  /// First paragraph top-left (screen pixels).
  external SHPoint start_top;

  /// First paragraph bottom-left (screen pixels).
  external SHPoint start_bottom;

  /// Last paragraph top-right (screen pixels).
  external SHPoint end_top;

  /// Last paragraph bottom-right (screen pixels).
  external SHPoint end_bottom;

  /// Mouse position when selection started (screen pixels).
  external SHPoint mouse_start;

  /// Mouse position when selection ended (screen pixels).
  external SHPoint mouse_end;

  /// Selection method (enum SHSelectionMethod).
  @ffi.Int32()
  external int method;

  /// Position level (enum SHPositionLevel).
  @ffi.Int32()
  external int pos_level;

  /// Fullscreen state of the source window (macOS only, 0=unknown/no, 1=yes).
  @ffi.Int32()
  external int is_fullscreen;
}

/// Selection method identifiers.
enum SHSelectionMethod {
  SH_METHOD_NONE(0),
  SH_METHOD_UIA(1),

  /// Removed upstream, kept for alignment.
  SH_METHOD_FOCUSCTL(2),
  SH_METHOD_ACCESSIBLE(3),
  SH_METHOD_AXAPI(11),

  /// @reserved AT-SPI method reserved for future use.
  SH_METHOD_ATSPI(21),
  SH_METHOD_PRIMARY(22),
  SH_METHOD_CLIPBOARD(99);

  final int value;
  const SHSelectionMethod(this.value);

  static SHSelectionMethod fromValue(int value) => switch (value) {
    0 => SH_METHOD_NONE,
    1 => SH_METHOD_UIA,
    2 => SH_METHOD_FOCUSCTL,
    3 => SH_METHOD_ACCESSIBLE,
    11 => SH_METHOD_AXAPI,
    21 => SH_METHOD_ATSPI,
    22 => SH_METHOD_PRIMARY,
    99 => SH_METHOD_CLIPBOARD,
    _ => throw ArgumentError('Unknown value for SHSelectionMethod: $value'),
  };
}

/// Position level identifiers.
enum SHPositionLevel {
  SH_POS_LEVEL_NONE(0),
  SH_POS_LEVEL_MOUSE_SINGLE(1),
  SH_POS_LEVEL_MOUSE_DUAL(2),
  SH_POS_LEVEL_SEL_FULL(3),
  SH_POS_LEVEL_SEL_DETAILED(4);

  final int value;
  const SHPositionLevel(this.value);

  static SHPositionLevel fromValue(int value) => switch (value) {
    0 => SH_POS_LEVEL_NONE,
    1 => SH_POS_LEVEL_MOUSE_SINGLE,
    2 => SH_POS_LEVEL_MOUSE_DUAL,
    3 => SH_POS_LEVEL_SEL_FULL,
    4 => SH_POS_LEVEL_SEL_DETAILED,
    _ => throw ArgumentError('Unknown value for SHPositionLevel: $value'),
  };
}

typedef SHSelectionCallbackFunction =
    ffi.Void Function(ffi.Pointer<SHSelectionData> data);
typedef DartSHSelectionCallbackFunction =
    void Function(ffi.Pointer<SHSelectionData> data);

/// Text selection callback.
///
/// Called from a native thread (CGEventTap RunLoop, Windows hook thread,
/// X11 event loop, etc.). The `data` pointer is valid ONLY for the duration
/// of the callback. Dart MUST copy any needed fields before returning.
///
/// Must be registered via sh_set_selection_callback before sh_start.
///
/// @param data Selection data. Lifetime = callback duration. Copy immediately.
typedef SHSelectionCallback =
    ffi.Pointer<ffi.NativeFunction<SHSelectionCallbackFunction>>;

/// Mouse/wheel event data.
///
/// event_type: 0=mouse-down, 1=mouse-up, 2=mouse-move, 3=mouse-wheel
/// button: None=-1, Left=0, Middle=1, Right=2, Back=3, Forward=4, Unknown=99.
/// For mouse-wheel: 0=Vertical, 1=Horizontal.
/// flag: wheel direction (1=Up/Right, -1=Down/Left; 0 for non-wheel events).
///
/// Sentinel INVALID_COORDINATE (-99999) applies to x/y on Linux Wayland.
final class SHMouseEventData extends ffi.Struct {
  @ffi.Int32()
  external int x;

  @ffi.Int32()
  external int y;

  @ffi.Int32()
  external int button;

  @ffi.Int32()
  external int event_type;

  @ffi.Int32()
  external int flag;
}

/// Keyboard event data.
///
/// uni_key: MDN KeyboardEvent.key value (UTF-8, NUL-terminated).
/// Library-owned, valid only during callback.
/// vk_code: Platform-specific virtual key code.
/// Windows=VK_*, macOS=kVK_*, Linux=KEY_* from linux/input-event-codes.h.
/// sys: Non-zero if Alt/Ctrl/Win/Cmd/Fn modifier pressed simultaneously.
/// flags: Additional platform-specific flags (Linux: modifier bitmask).
final class SHKeyboardEventData extends ffi.Struct {
  external ffi.Pointer<ffi.Char> uni_key;

  @ffi.Int32()
  external int vk_code;

  @ffi.Int32()
  external int sys;

  @ffi.Int32()
  external int flags;
}

typedef SHMouseCallbackFunction =
    ffi.Void Function(ffi.Pointer<SHMouseEventData> data);
typedef DartSHMouseCallbackFunction =
    void Function(ffi.Pointer<SHMouseEventData> data);

/// Mouse event callback. data valid only during callback.
typedef SHMouseCallback =
    ffi.Pointer<ffi.NativeFunction<SHMouseCallbackFunction>>;
typedef SHKeyboardCallbackFunction =
    ffi.Void Function(ffi.Pointer<SHKeyboardEventData> data);
typedef DartSHKeyboardCallbackFunction =
    void Function(ffi.Pointer<SHKeyboardEventData> data);

/// Keyboard event callback. data valid only during callback.
typedef SHKeyboardCallback =
    ffi.Pointer<ffi.NativeFunction<SHKeyboardCallbackFunction>>;

/// Configuration for text selection monitoring.
/// All fields are optional — pass 0 for defaults.
final class SHSelectionConfig extends ffi.Struct {
  /// 1=enable diagnostic logging
  @ffi.Int32()
  external int debug;

  /// 1=enable high-CPU mouse-move events
  @ffi.Int32()
  external int enable_mouse_move;

  /// 1=enable clipboard fallback (default: 1)
  @ffi.Int32()
  external int enable_clipboard;

  /// 1=require manual trigger for selection
  @ffi.Int32()
  external int selection_passive_mode;

  /// FilterMode: 0=Default, 1=IncludeList, 2=ExcludeList
  @ffi.Int32()
  external int clipboard_mode;

  /// FilterMode for global program filter
  @ffi.Int32()
  external int global_filter_mode;
}

const int SH_OK = 0;

const int SH_ERR_GENERIC = -1;

const int SH_ERR_INVALID_ARG = -2;

const int SH_ERR_ALREADY_RUNNING = -3;

const int SH_ERR_NOT_RUNNING = -4;

const int SH_ERR_NOT_TRUSTED = -5;
